name: Api Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Get public IP Address
      - name: Get public IP address
        run: |
          curl ifconfig.me
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
